import Head from 'next/head'
import Image from 'next/image'
import React, { useState } from 'react';
import styles from '../styles/Home.module.css'
import ArrowBackIcon from '@mui/icons-material/ArrowBack';

export default function Home() {
  //inputText =get เอาไปเเสดง
  //setInputText =เอาค่า
  const [inputText, setInputText] = useState();
  const [listAR, setListAR] = useState();
  const [positionX, setPositionX] = useState();
  const [positionY, setPositionY] = useState();
  const [result, setResult] = useState([]);

  const table = [
    ["-4, 4", "-3, 4", "-2, 4", "-1, 4", "0, 4", "1, 4", "2, 4", "3, 4", "4, 4"],
    ["-4, 3", "-3, 3", "-2, 3", "-1, 3", "0, 3", "1, 3", "2, 3", "3, 3", "4, 3"],
    ["-4, 2", "-3, 2", "-2, 2", "-1, 2", "0, 2", "1, 2", "2, 2", "3, 2", "4, 2"],
    ["-4, 1", "-3, 1", "-2, 1", "-1, 1", "0, 1", "1, 1", "2, 1", "3, 1", "4, 1"],
    ["-4, 0", "-3, 0", "-2, 0", "-1, 0", "0, 0", "1, 0", "2, 0", "3, 0", "4, 0"],
    ["-4, -1", "-3, -1", "-2, -1", "-1, -1", "0, -1", "1, -1", "2, -1", "3, -1", "4, -1"],
    ["-4, -2", "-3, -2", "-2, -2", "-1, -2", "0, -2", "1, -2", "2, -2", "3, -2", "4, -2"],
    ["-4, -3", "-3, -3", "-2, -3", "-1, -3", "0, -3", "1, -3", "2, -3", "3, -3", "4, -3"],
    ["-4, -4", "-3, -4", "-2, -4", "-1, -4", "0, -4", "1, -4", "2, -4", "3, -4", "4, -4"],
  ]


  var area = [];

  const setArea = (summax) => {
    //จองพื้นที่ใน Array ตามขนาด summax = cont "W"
    console.log("cubes", area);
    for (var x = 0; x < summax; x++) {
      for (var y = 0; y < summax; y++) {
        //console.log("in j", j);
        let arr = { x, y };
        area.push(arr);
      }
    }
    console.log("in area", area);
  }

  const printLastArea = (summax) => {
    //เเสดงข้อมูลที่มีการเดินเข้าไปในใน Array
    for (var x = 0; x < summax; x++) {
      for (var y = 0; y < summax; y++) {
        console.log('[' + x + ',' + y + ']');

      }
    }

  }

  //สร้างฟังค์ชัน
  const clickBtn = () => {
    console.log(inputText);
    const command = inputText.split("");
    const maxText = command.filter((i) => i == 'W')


    console.log(maxText);
    let summax = (maxText.length + maxText.length) + 1;
    console.log(typeof summax);


    setArea(summax);
    area[maxText.length][maxText.length] = '#';
    //console.log(area);
    //area[0][0] = '#';
    //fi == เเกน y
    //se == เเกน x
    let fi = maxText.length;
    let se = maxText.length;
    let status = 0;
    var cubes = [];

    for (let i = 0; i < command.length; i++) {
      if (command[i] != ' ') {
        //เช็คเมื่อเจอค่าจริง
        if (command[i] == 'W') {
          console.log("status", command[i], " : ", status);
          if (status == 0) {
            fi--;
          }
          if (status == 1) {
            se--;
          }
          if (status == 2) {
            fi++;
          }
          if (status == 3) {
            se++;
          }
          console.log("fi", fi);
          console.log("se", se);
          area[fi][se] = 'o';
        }


        if (command[i] == 'L') {
          status++;
          console.log("L", command[i], " : ", status);
        }

        if (command[i] == 'R') {

          if (status == 0) {
            status = 3;
          }
          else {
            status--;
          }
          console.log("status", command[i], " : ", status);
        }

        if (status == 4) {
          status = 0;
        }
      }
      else {
        break;
      }
    }

    area[fi][se] = '@';
    console.log("index se,fi =", se, fi);
    printLastArea(summax);
    setListAR(area);
    let x
    let y
    x = se - maxText.length;
    y = maxText.length - fi;

    setPositionX(x);
    setPositionY(y);
    console.log("index x,y =", x, y);
    // -----------------
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


      </Head>
      <div className='box1'>
        <div style={{paddingBottom:"20px"}}>
          <a href="/">
          < ArrowBackIcon />
          </a>
          </div>
        <div class="row" >
          <div class="col-sm">
            <div className='box2'>
              <div>
                <h3>Robot Walk</h3>
              </div>
              <div>
                <h6>คำสั่ง Robot Walk</h6>
                <div> L - หันซ้าย </div>
                <div>R - หันขวา</div>
                <div>W – เดินไปด้านหน้าตามทิศทางที่หัน</div>
              </div>
              <input value={inputText} type="text" id="lname" name="lastname" placeholder="" onChange={(e) => setInputText(e.target.value)} />
              <div style={{ padding: "10px", }}>
                <button class="button" onClick={() => clickBtn()}>คำนวณ
                </button>
              </div>
            </div>
          </div>
          <div class="col-sm">
            <div className='setText'> ตำเเหน่งปัจจุบัน : ({positionX} , {positionY})</div>

            <div>
              {table.map((items, index) => {
                return (
                  <div style={{ display: 'flex' }}>
                    {items.map((subItems, sIndex) => {
                      const resultData = result.find(r => r === subItems)

                      return <div style={{ width: 20, height: 20, backgroundColor: subItems === '0, 0' ? '#36FF00' : subItems === resultData ? '#D8D8D8' : '#ffffff', border: '2px solid black' }}>  </div>;
                    })}
                  </div>
                );
              })}
            </div>
          </div>

        </div>
      </div>
      {console.log(listAR)}
    </div>
  )
}
