import Head from 'next/head'
import ArrowDownwardIcon from '@mui/icons-material/ArrowDownward';
import EqualizerIcon from '@mui/icons-material/Equalizer';
import { Carousel } from 'react-responsive-carousel';
import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader
import ArrowUpwardIcon from '@mui/icons-material/ArrowUpward';
import EventNoteIcon from '@mui/icons-material/EventNote';
import RestaurantIcon from '@mui/icons-material/Restaurant';
import PaidIcon from '@mui/icons-material/Paid';
import ShoppingBasketIcon from '@mui/icons-material/ShoppingBasket';

export default function Home() {

  //เปลี่ยนหน้า
  const onClickCard = (path) => {
    window.location.href = `/${path}`;
  };

  return (
    <div >
      <Head>
        <title>ViSa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Prompt:wght@300&family=Roboto&display=swap" rel="stylesheet" />
      </Head>

      <div style={{ padding: 20 }}>

        <div className='boxbetween'>
          <div>
            <div className='textblueh1'> All my accounts</div>
          </div>
          <div className='iconbule'>
            <EqualizerIcon />
          </div>
        </div>

        <div className="textleft">
          <div className='textgrey3'>June 10,2018</div>
        </div>





        <div >
          <Carousel
            showThumbs={false}
            showArrows={false}
            showStatus={false}>
            <div onClick={() => onClickCard("visaDetail")} >
              <img src="visa-1.png" />
            </div>
            <div onClick={() => onClickCard("visaDetail")} >
              <img src="visa-2.png" />
            </div>
            <div onClick={() => onClickCard("visaDetail")} >
              <img src="visa-3.png" />
            </div>
            {/* <!-- Card --> */}
    <div class="card">
      {/* <!-- ส่วนที่ 1 --> */}
      <div class="content">
        <div class="image">
          {/* <img src="./visa-logo.png" class="visa" width="60" />
          <img src="./chip.png" class="chip" width="40" height="30" /> */}
        </div>
        <div class="detail-amount">
          <div class="status">Available Balance</div>
          <div class="amount">$ 7,392.00</div>
        </div>
      </div>
      {/* <!-- ส่วนที่ 2 --> */}
      <div class="content-digit">
        <div>42012</div>
        <div>3049</div>
        <div>2800</div>
        <div>9815</div>
      </div>
      {/* <!-- ส่วนที่ 3 --> */}
      <div class="expire">
        {/* <!-- Expiration date --> */}
        <div class="expire-centent">
          <span class="title">EXPIRE</span>
          <span>02/22</span>
        </div>
        {/* <!-- CVC Code --> */}
        <div class="expire-centent">
          <span class="title">CVC CODE</span>
          <span>230</span>
        </div>
      </div>
    </div>
          </Carousel>
        </div>

        <div style={{ padding: "8px 0px 10px 0", }}>
          <div className='boxstyle2'>
            <div style={{ width: "50%" }}>
              <div style={{ padding: "0px 40px 5px 40px" }}>
                <div className='boxstyle4'>Income</div>
              </div>
              <div className='divrowgreen'>
                <ArrowDownwardIcon />
                <div style={{ padding: "0px 0px 0px 5px" }}>$9,302.00</div>
              </div>

            </div>
            <div
              style={{
                width: "50%",
              }}
            >
              <div style={{ padding: "0px 40px 5px 40px" }}>
                <div className='boxstyle4'>Expense</div>
              </div>

              <div className='divrowred'>
                <ArrowUpwardIcon />
                <div style={{ padding: "0px 0px 0px 5px" }}>$2,790.00</div>
              </div>
            </div>
          </div>
        </div>

        <div className='boxspace'>
          <div className='boxbetween'>
            <div>
              <div className='textblueh3'> Detail of movements</div>
            </div>
            <div className='iconbule' style={{ paddingBottom: "10px" }}>
              <EventNoteIcon />
            </div>
          </div>

          <div className='boxstyle2' >
            <div className='icon'>
              <RestaurantIcon />
            </div>
            <div style={{ width: "70%", }}>
              <div class="textleft">Restaurant Manhattan</div>
              <div class="textleft2">June 2,2018</div>
            </div>
            <div className='divrowred-2'>
              <div style={{ padding: "0px 5px 0px 0px" }}>$170</div>
              <ArrowUpwardIcon />
            </div>
          </div>
        </div>

        <div className='boxspace'>
          <div className='boxstyle2'>
            <div className='icon'>
              <PaidIcon />
            </div>
            <div style={{ width: "70%", }}>
              <div class="textleft">Salary Deposit</div>
              <div class="textleft2">June 2,2018</div>
            </div>
            <div className='divrowgreen-2'>
              <div style={{ padding: "0px 5px 0px 0px" }}>$1,200</div>
              <ArrowDownwardIcon />
            </div>
          </div>
        </div>

        <div className='boxspace'>
          <div className='boxstyle2'>
            <div className='icon'>
              <ShoppingBasketIcon />
            </div>
            <div style={{ width: "70%", }}>
              <div class="textleft">Central Market Deposit</div>
              <div class="textleft2">May 2,2018</div>
            </div>
            <div className='divrowred-2'>
              <div style={{ padding: "0px 5px 0px 0px" }}>$170</div>

              <ArrowUpwardIcon />

            </div>
          </div>
        </div>
        <div className='boxspace'>
          <div className='boxstyle2'>
            <div className='icon'>
              <PaidIcon />
            </div>
            <div style={{ width: "70%", }}>
              <div class="textleft">Salary Deposit</div>
              <div class="textleft2">June 2,2018</div>
            </div>
            <div className='divrowgreen-2'>
              <div style={{ padding: "0px 5px 0px 0px" }}>$1,200</div>
              <ArrowDownwardIcon />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
